name: Tests

on:
  push:
    branches: [ master, rc/* ]
  pull_request:
    branches: [ master, rc/* ]

jobs:
  test:
    name: Unit tests without race detector
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17.6
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.6
        id: go

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Unit tests
        run: make test
  test-race:
    name: Unit tests with race detector
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17.6
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.6
        id: go

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Unit tests
        run: make test-race
